BidSignalR/Controllers/LotController.cs
using Demo.MedTech.DataModel.Shared;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Options;
using Playground.Models;
using Playground.Policies;
using Playground.Services.IServices;
using RestSharp;
using System;
using System.Text;
using System.Text.Json;

namespace Playground.Controllers
{
    public class EgressLotDetail : LotDetail
    {
        public bool EgressIsPiecemeal
        {
            get => false;
            set {; }
        }
    }

    public class LotController : Controller
    {
        private readonly IRestClientApiCall _restClientApiCall;
        private static IConfiguration _configuration;
        private readonly CosmosPollySettings _cosmosPollySettings;

        public LotController(IRestClientApiCall restClientApiCall, IConfiguration configuration, IOptions<CosmosPollySettings> cosmosOptions)
        {
            _restClientApiCall = restClientApiCall;
            _configuration = configuration;
            _cosmosPollySettings = cosmosOptions.Value;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult VerifyLot(EgressLotDetail lotDetails)
        {
            var request = new RestRequest(Method.POST);
            request.AddHeader("Content-Type", "application/json");
            request.AddParameter("application/json", JsonSerializer.Serialize(lotDetails), ParameterType.RequestBody);

            IRestResponse response = _restClientApiCall.Execute(request, _configuration["INGRESS_API"] + _configuration["VERIFY_LOT_ENDPOINT"]);
            return Ok(response.Content);
        }

        [HttpPost]
        public ActionResult CreateLot(EgressLotDetail lotDetails)
        {
            var request = new RestRequest(Method.POST);
            StringBuilder correlation = new StringBuilder();

            string correlationId = correlation.Append(DateTimeOffset.Now.ToUnixTimeSeconds())
            .Append("SBS")
            .Append("PLAY")
            .Append(Guid.NewGuid().ToString("N").Substring(0, 15))
            .ToString();

            request.AddHeader("x-correlation-id", correlationId);
            request.AddParameter("application/json", JsonSerializer.Serialize(CreateLotObj(lotDetails)),
                ParameterType.RequestBody);

            IRestResponse response = _restClientApiCall.Execute(request, _configuration["INGRESS_API"] + _configuration["LOT_LATEST_DETAILS_ENDPOINT"]);

            //if (response.StatusCode == HttpStatusCode.OK)
            //{
            //    var policy = RetryPolicy.GetCosmosAsyncPolicy(_cosmosPollySettings.RetryTimeInSeconds, _cosmosPollySettings.RetryCount, _cosmosPollySettings.TimeoutPeriodInSeconds);
            //    _ = Task.Run(async () =>
            //    {
            //        await policy.ExecuteAsync(async (ct) =>
            //        {
            //            await _cosmosRepo.ResetLotAsync(lotDetails.AuctionId, lotDetails.LotId);
            //        }, new CancellationToken());
            //    }).ConfigureAwait(false);
            //}

            return Ok(response.Content == "" ? response?.ErrorException?.Message : response.Content);
        }

        [HttpPut]
        public ActionResult UpdateLot(EgressLotDetail lotDetails)
        {
            var request = new RestRequest(Method.POST);
            StringBuilder correlation = new StringBuilder();

            string correlationId = correlation.Append(DateTimeOffset.Now.ToUnixTimeSeconds())
                .Append("SBS")
                .Append("PLAY")
                .Append(Guid.NewGuid().ToString("N").Substring(0, 15))
                .ToString();

            request.AddHeader("x-correlation-id", correlationId);
            request.AddParameter("application/json", JsonSerializer.Serialize(CreateLotObj(lotDetails)),
                ParameterType.RequestBody);

            IRestResponse response = _restClientApiCall.Execute(request, _configuration["INGRESS_API"] + _configuration["LOT_UPDATE_DETAILS_ENDPOINT"]);

            //if (response.StatusCode == HttpStatusCode.OK)
            //{
            //    var policy = RetryPolicy.GetCosmosAsyncPolicy(_cosmosPollySettings.RetryTimeInSeconds, _cosmosPollySettings.RetryCount, _cosmosPollySettings.TimeoutPeriodInSeconds);
            //    _ = Task.Run(async () =>
            //    {
            //        await policy.ExecuteAsync(async (ct) =>
            //        {
            //            await _cosmosRepo.ResetLotAsync(lotDetails.AuctionId, lotDetails.LotId);
            //        }, new CancellationToken());
            //    }).ConfigureAwait(false);
            //}

            return Ok(response.Content == "" ? response?.ErrorException?.Message : response.Content);
        }

        [HttpDelete]
        public ActionResult DeleteLot(long auctionId, long lotId)
        {
            string url = _configuration["INGRESS_API"] + _configuration["DELETE_LOT_ENDPOINT"] + $"?auctionId={auctionId}&lotId={lotId}";
            var request = new RestRequest(Method.DELETE);
            StringBuilder correlation = new StringBuilder();

            string correlationId = correlation.Append(DateTimeOffset.Now.ToUnixTimeSeconds())
                .Append("SBS")
                .Append("PLAY")
            .Append(Guid.NewGuid().ToString("N").Substring(0, 15))
            .ToString();

            request.AddHeader("Content-Type", "application/json");
            request.AddHeader("x-correlation-id", correlationId);

            IRestResponse response = _restClientApiCall.Execute(request, url);
            //if (response.StatusCode == HttpStatusCode.OK)
            //{
            //    var policy = RetryPolicy.GetCosmosAsyncPolicy(_cosmosPollySettings.RetryTimeInSeconds, _cosmosPollySettings.RetryCount, _cosmosPollySettings.TimeoutPeriodInSeconds);
            //    _ = Task.Run(async () =>
            //    {
            //        await policy.ExecuteAsync(async (ct) =>
            //        {
            //            await _cosmosRepo.ResetLotAsync(auctionId, lotId);
            //        }, new CancellationToken());
            //    }).ConfigureAwait(false);
            //}

            if (response.Content == "")
            {
                response.Content = "{\"isValid\":true,\"validationResults\":[]}";
            }

            return Ok(response.Content);
        }

        private EgressLotModel CreateLotObj(LotDetail lotDetails)
        {
            return new EgressLotModel()
            {
                Domain = "SBS",
                SubDomain = "Auctioneer",
                LotId = lotDetails.LotId,
                AuctionId = lotDetails.AuctionId,
                LotDetail = lotDetails,
            };
        }
    }
}

BidSignalR/Views/Shared/_Layout.cshtml
@using Microsoft.Extensions.Configuration
@inject IConfiguration Configuration

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Playground</title>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/site.css" />
    <script>
        const basePath = "@Configuration.GetSection("BasePath").Value";
    </script>
</head>
<body>
    <header>
        <nav>
            @* Note: While adding menu change menu hover css accordingly*@
            <a asp-controller="Lot" asp-action="" id="CreateLot">Auction Lot</a>
            <div class="animation start-home"></div>
        </nav>
    </header>
    <div class="container" style="max-width:1800px !important">
        <main role="main" class="pb-3">
            <div class="overlay"></div>
            <div class="spanner">
                <div class="loader"></div>
                @*<p>Loading...</p>*@
                <svg style="height: 100px" version="1.1" id="L9" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                     viewBox="0 0 100 100" enable-background="new 0 0 0 0" xml:space="preserve">
                <path fill="#fff" d="M73,50c0-12.7-10.3-23-23-23S27,37.3,27,50 M30.9,50c0-10.5,8.5-19.1,19.1-19.1S69.1,39.5,69.1,50">
                <animateTransform attributeName="transform"
                                  attributeType="XML"
                                  type="rotate"
                                  dur="1s"
                                  from="0 50 50"
                                  to="360 50 50"
                                  repeatCount="indefinite" />
                    </path>
                </svg>
            </div>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Auction App
        </div>
    </footer>

    @if (ViewData["Active"] != null)
    {
        <script type="text/javascript">document.getElementById("@ViewData["Active"]").classList.add("active")</script>
    }

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript">
        function showLoader() {
            $("div.spanner").addClass("show");
            $("div.overlay").addClass("show");
        }
        function hideLoader() {
            $("div.spanner").removeClass("show");
            $("div.overlay").removeClass("show");
        }
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>